import fs from 'node:fs';
import { chromium } from 'playwright';

fs.mkdirSync('evidence', { recursive: true });
const browser = await chromium.launch({ headless: true });
const page = await browser.newPage({ viewport: { width: 1280, height: 900 }, deviceScaleFactor: 1 });
const errors = [];
page.on('pageerror', error => errors.push(String(error)));
page.on('console', message => { if (message.type() === 'error') errors.push(message.text()); });
await page.goto('http://127.0.0.1:4173/', { waitUntil: 'networkidle' });
await page.screenshot({ path: 'evidence/initial.png', fullPage: true });
if (errors.length) throw new Error(`page errors: ${errors.join(' | ')}`);
const canvas = page.locator('canvas#game');
if (await canvas.count() !== 1) throw new Error('game canvas missing');
const initial = await canvas.screenshot({ path: 'evidence/canvas-initial.png' });
if (initial.length < 1000) throw new Error(`canvas screenshot suspiciously small: ${initial.length}`);
if (await page.locator('#sound').getAttribute('aria-pressed') !== 'false') throw new Error('sound default is not on');
await page.locator('#sound').click();
if (await page.locator('#sound').getAttribute('aria-pressed') !== 'true') throw new Error('sound toggle did not mute');
await page.locator('#sound').click();
if (await page.locator('#sound').getAttribute('aria-pressed') !== 'false') throw new Error('sound toggle did not unmute');
await page.locator('[data-key="attack"]').dispatchEvent('pointerdown');
await page.locator('[data-key="attack"]').dispatchEvent('pointerup');
await page.screenshot({ path: 'evidence/after-controls.png', fullPage: true });
const mobile = await browser.newPage({ viewport: { width: 390, height: 844 }, hasTouch: true, isMobile: true });
await mobile.goto('http://127.0.0.1:4173/', { waitUntil: 'networkidle' });
if (await mobile.locator('.pad').isHidden()) throw new Error('touch pad hidden on mobile');
await mobile.screenshot({ path: 'evidence/mobile.png', fullPage: true });
console.log('BROWSER SMOKE OK 8/8');
await browser.close();
