import fs from 'node:fs';
import assert from 'node:assert/strict';
import { createGame, step, WORLD } from '../src/game.mjs';

const contract = JSON.parse(fs.readFileSync(new URL('../game-contract.json', import.meta.url), 'utf8'));
assert.equal(contract.title, '赵云和阿斗');
assert.equal(contract.platform, 'browser');
assert.equal(contract.first_playable_slice.camera, '俯视 3D');
assert.equal(contract.first_playable_slice.player, '赵云');
assert.equal(contract.first_playable_slice.protected_character, '阿斗');
assert.ok(contract.machine_proof.includes('npm run verify'));
assert.ok(contract.human_acceptance.includes('mobile touch feel is not machine-confirmed'));
const raw = fs.readFileSync(new URL('../game-contract.json', import.meta.url), 'utf8');
assert.equal(/(ghp_|github_pat_|sk-[A-Za-z0-9])/.test(raw), false);
const initial = createGame(7);
assert.equal(initial.status, 'playing');
assert.equal(initial.enemies.length, 2);
const moved = step(initial, { right: true }, 1);
assert.ok(moved.zhao.x > initial.zhao.x);
assert.ok(moved.zhao.x <= WORLD.width - 0.6);
const replayA = step(createGame(7), { right: true, down: true }, 0.25);
const replayB = step(createGame(7), { right: true, down: true }, 0.25);
assert.deepEqual(replayA, replayB);
let win = createGame(7); win.dou.x = WORLD.exit.x; win.dou.y = WORLD.exit.y; win = step(win, {}, 0.01); assert.equal(win.status, 'won');
let lose = createGame(7); lose.dou.hp = 1; lose.enemies = [{ id: 'test', x: lose.dou.x, y: lose.dou.y, speed: 0, cooldown: 0 }]; lose = step(lose, {}, 1.1); assert.equal(lose.status, 'lost');
console.log('PASS contract: Zhao Yun and A Dou top-down 3D slice');
console.log('PASS movement: bounds and deterministic replay');
console.log('PASS outcomes: win and loss are reachable');
console.log('VERIFY OK 3/3');
